"""
Visualization Module - plotting and visualization of results.
"""

import numpy as np
import matplotlib.pyplot as plt
from typing import Tuple
from ParametricModel import ParametricModel


class Visualizer:
    def __init__(self, model: ParametricModel, figsize: Tuple[int, int] = (12, 10), dpi: int = 300):

        self.model = model
        self.figsize = figsize
        self.dpi = dpi
    
    def plot_fit(self, x_obs: np.ndarray, y_obs: np.ndarray, t_grid: np.ndarray, # Renamed t to t_grid for clarity
                 theta_opt: float, m_opt: float, x_opt: float,
                 loss_value: float, save_path: str = 'fit_plot.png') -> None:
        """
        Plots the observed data points and the curve generated by the optimized parameters.
        
        The residuals plot is excluded due to the unknown t-values for observations.
        """
        
        # 1. Predictions: Use the fine t_grid to generate the smooth predicted curve
        x_pred, y_pred = self.model.predict(t_grid, theta_opt, m_opt, x_opt)
        
        plt.figure(figsize=self.figsize, dpi=self.dpi)
        
        # Plot 1: Observed vs Predicted curve
        plt.scatter(x_obs, y_obs, alpha=0.6, s=20, label='Observed Points (N=1501)', 
                    color='#007ACC', marker='o') # Blue-like
        plt.plot(x_pred, y_pred, color='#D35400', linewidth=2.5, label='Predicted Curve (Fitted)', alpha=0.9) # Orange-like
        
        plt.xlabel('x coordinate', fontsize=14)
        plt.ylabel('y coordinate', fontsize=14)
        
        # Add a text box for the key results
        textstr = '\n'.join((
            r'$\mathbf{\theta_{\text{opt}}} = %.4f$' % (theta_opt, ),
            r'$\mathbf{M_{\text{opt}}} = %.4f$' % (m_opt, ),
            r'$\mathbf{X_{\text{opt}}} = %.4f$' % (x_opt, ),
            r'$\mathbf{Mean\ L1\ Loss} = %.5f$' % (loss_value, )
        ))
        
        # Place the key results box on the plot
        props = dict(boxstyle='round', facecolor='white', alpha=0.8, edgecolor='gray')
        plt.gca().text(0.05, 0.95, textstr, transform=plt.gca().transAxes, fontsize=12,
                       verticalalignment='top', bbox=props)
        
        plt.title(f'Final Curve Fit (Mean L1 Loss: {loss_value:.6f})', fontsize=16, fontweight='bold')
        plt.legend(loc='lower right', fontsize=11)
        plt.grid(True, alpha=0.3, linestyle='--')
        plt.gca().set_aspect('equal', adjustable='box') # Ensure proper aspect ratio
        
        plt.tight_layout()
        plt.savefig(save_path, dpi=self.dpi, bbox_inches='tight')
        print(f"\n✓ Final Curve Fit visualization saved to {save_path}")
        plt.close()
        

    
    def plot_optimization_history(self, history: list, save_path: str = 'optimization_history.png') -> None:
        """
        Ploting optimization history
        """
        if not history:
            print("No optimization history available.")
            return
        
        methods = [step['method'] for step in history]
        thetas = [step['theta'] for step in history]
        ms = [step['m'] for step in history]
        xs = [step['x'] for step in history]
        losses = [step['loss'] for step in history]
        
        _, axes = plt.subplots(2, 2, figsize=(14, 10))
        
        xlabel = 'Optimization Step'
        
        # Plot 1: Loss evolution
        ax1 = axes[0, 0]
        ax1.plot(range(len(losses)), losses, 'bo-', linewidth=2, markersize=8)
        ax1.set_xlabel(xlabel, fontsize=12)
        ax1.set_ylabel('L1 Loss', fontsize=12)
        ax1.set_title('Loss Evolution', fontsize=14, fontweight='bold')
        ax1.grid(True, alpha=0.3)
        for i, method in enumerate(methods):
            ax1.text(i, losses[i], method, fontsize=8, ha='center', va='bottom')
        
        # Plot 2: Theta evolution
        ax2 = axes[0, 1]
        ax2.plot(range(len(thetas)), thetas, 'ro-', linewidth=2, markersize=8)
        ax2.set_xlabel(xlabel, fontsize=12)
        ax2.set_ylabel('θ (degrees)', fontsize=12)
        ax2.set_title('Theta Evolution', fontsize=14, fontweight='bold')
        ax2.grid(True, alpha=0.3)
        
        # Plot 3: M evolution
        ax3 = axes[1, 0]
        ax3.plot(range(len(ms)), ms, 'go-', linewidth=2, markersize=8)
        ax3.set_xlabel(xlabel, fontsize=12)
        ax3.set_ylabel('M', fontsize=12)
        ax3.set_title('M Evolution', fontsize=14, fontweight='bold')
        ax3.grid(True, alpha=0.3)
        
        # Plot 4: X evolution
        ax4 = axes[1, 1]
        ax4.plot(range(len(xs)), xs, 'mo-', linewidth=2, markersize=8)
        ax4.set_xlabel(xlabel, fontsize=12)
        ax4.set_ylabel('X', fontsize=12)
        ax4.set_title('X Evolution', fontsize=14, fontweight='bold')
        ax4.grid(True, alpha=0.3)
        
        plt.tight_layout()
        plt.savefig(save_path, dpi=self.dpi, bbox_inches='tight')
        print(f"✓ Optimization history plot saved to {save_path}")
        plt.close()

# # run the code
# if __name__ == "__main__":
#     model = ParametricModel()
#     visualizer = Visualizer(model)
#     visualizer.plot_fit(x_obs, y_obs, t, theta_opt, m_opt, x_opt, 'fit_plot.png')
#     visualizer.plot_optimization_history(history, 'optimization_history.png')
#     print("✓ Visualization saved to fit_plot.png and optimization_history.png")